---
title: "US Foreign Policy"
description: "POLSC 343 Fall 2021 course page"
site: distill::distill_website
---

Welcome, this page will serve as the homepage for POLSC 343 US foreign policy (Fall 2021).

## Course Summary
 
This course focuses on the development of US foreign policy over the
course of the twentieth and twenty-first centuries. It will provide a brief background
on the history of US foreign policy before 1900, but will focus primarily on the developments and issues
occurring from 1900 through the present. The historical content of the course will be supplemented by
introducing students to political science literature that can help to identify and explain key events and trends
in US foreign policy during this time period. 

## Course Objectives

1. The overarching goal is to develop an understanding
of the systematic forces that shape US foreign policymaking. Please note that this is different than
prescribing what policy *should* be (though this is also an important consideration when considering our motivations for studying the topic and reading course materials.
2. Identify the key actors that influence foreign policy.
3. Understand how and when the influence of actors varies (e.g. across time, issue area, etc.).
4. Identify the key issues confronting policymakers and society. 
5. Identify general trends in US foreign policy over time. 
    - What's changed? 
    - What stays the same?
    - When and why do we see changes in behavior or policies?
6. Students should develop a familiarity with social science research processes, practices. Specifically, students should have:
    - A basic understanding of how to read social scientific research articles. 
    - A basic understanding of research design considerations
    - A basic understanding of what the scope and limitations of research articles


